name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-11, ubuntu-22.04]
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install automake
      - uses: secondlife/action-autobuild@v3
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
